class Config:
    HEX_SIZE = 30
    MIN_HEX_SIZE = 15
    MAX_HEX_SIZE = 60
    WIDTH = 400
    HEIGHT = 400
    GRID_WIDTH, GRID_HEIGHT = 65, 65
    FPS = 15
    UNIT_MOVEMENT_POINTS = 3
    DEFAULT_HEALTH = 100.0
    DEFAULT_ATTACK_POWER = 20.0
    DEFAULT_DEFENSE = 10.0
    ATTACK_RANGE = 1.5 * HEX_SIZE  # Approx. 1 hex distance